config/routes.rb
Rails.application.routes.draw do
    # トップページ用
    get "/bblogs/home/index" , to: "home#index"
    #   root to: "home#index"

    # ユーザー情報管理
    resources :users, only:[:new, :create, :show]
    
    # ログイン機能
    resources :sessions, only:[:new, :create, :destroy]
    
    # ブログ機能
    resources :bblogs do
        collection do
            post :confirm
        end
    end
    
    # お気に入り機能
    resources :favorites, only:[:create, :destroy]
    
    # 開発環境でのみletter_opener_webを使い、メール送信機能を確認
    if Rails.env.development?
        mount LetterOpenerWeb::Engine, at: "/letter_opener"
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bblog.rb
class Bblog < ApplicationRecord
    validates :name, presence: true
    validates :content, presence: true, length: {in: 1..140}
    
    # 1:多モデルの定義
    has_many :favorites, dependent: :destroy
    # favorite_usersという名のメソッドで、usersテーブルにアクセス
    has_many :favorite_users, through: :favorites, source: :user
    
    # アップローダーの定義
    mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # 中間テーブル
  belongs_to :user
  belongs_to :bblog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,
                  length: {maximum: 30}
  validates :email, presence: true,
                  length: {maximum: 255},
                  format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}

  # DBに保存前に、emailを小文字にする
  before_save {email.downcase!}
  
  # パスワードをハッシュ化するため、has_secure_passwordメソッドを使う
  has_secure_password
  validates :password, presence: true,
                    length: {minimum: 6}
  
  # 1:多モデル定義
  has_many :favorites, dependent: :destroy
  # favorite_bblogsという名のメソッドで、bblogsテーブルからデータ取得
  has_many :favorite_bblogs, through: :favorites, source: :bblog
  
  # 画像アップローダーとモデルの紐付け
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # 全コントローラーで使えるよう、sessinosmoduleをインクルード
  include SessionsHelper
  
  # フラッシュメッセージにnotice,alert以外のキーを許可する
  add_flash_types :success, :info, :warning, :danger
end

app/controllers/bblogs_controller.rb
class BblogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    before_action :correct_user, only: [:new, :edit, :show, :destroy]

    def index
        @bblogs = Bblog.all
#        binding.pry
#        raise
    end
    
    def new
        if params[:back]
            @bblog = Bblog.new(blog_params)
        else
            @bblog = Bblog.new
        end
    end
    
    def create
#        Bblog.create(name: params[:bblog][:title], content: params[:bblog][:content])
#        Bblog.create(params.require(:bblog).permit(:name, :content))
#        Bblog.create(blog_params)
        @bblog = Bblog.new(blog_params)
        @bblog.user_id = current_user.id
        # キャッシュから画像を復元
        @bblog.image.retrieve_from_cache! params[:cache][:image]
        if @bblog.save
            redirect_to bblogs_path, notice: "ブログを作成しました"
        else
#            redirect_to new_bblog_path
            render "new"
        end
    end
    
    # 詳細ページが呼び出されたとき、blog記事とお気に入りを取得する
    def show
        # @bblog = Bblog.find(params[:id])
        @favorite = current_user.favorites.find_by(bblog_id: @bblog.id)
    end
    
    def edit
        # @bblog = Bblog.find(params[:id])
    end
    
    def update
        # @bblog = Bblog.find(params[:id])
        if @bblog.update(blog_params)
            redirect_to bblogs_path, notice:"編集しました"
        else
            render "edit"
        end
    end
    
    def destroy
        @bblog.destroy
        redirect_to bblogs_path, notice:"削除したよ"
    end
    
    def confirm
        @bblog =Bblog.new(blog_params)
        render :new if @bblog.invalid?
    end
    
    private
    
    def blog_params
        params.require(:bblog).permit(:name, :content, :image)
    end
    
    def set_blog
        @bblog = Bblog.find(params[:id])
    end
    
    # カレントユーザーが存在しない場合、強制的にログイン画面にリダイレクト
    def correct_user
        if !logged_in?
            flash[:warning] = "ログインしてください"
            redirect_to new_session_path
        end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  # お気に入りする
  def create
    favorite = current_user.favorites.create(bblog_id: params[:bblog_id])
    redirect_to bblogs_path
  end
  
  # お気に入り解除する
  def destroy
    favorite = current_user.favorites.find_by(bblog_id: params[:bblog_id]).destroy
    redirect_to bblogs_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:success] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only:[:create, :show]
  
  def new
    @user = User.new
  end
  
  # 入力ユーザー情報がDBに保存されたとき、メール送信する
  def create
    @user = User.new(user_params)
    # キャッシュから画像を復元 ← 確認画面を挟まないので不要
    # @user.image.retrieve_from_cache! params[:cache][:image]
    if @user.save
      ContactMailer.send_email(@user).deliver
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end
  
  def show
    @user = User.find(params[:id])
    @favorite_bblogs = @user.favorite_bblogs
  end
  
  private
  
  # 別ユーザーのページに、直URLでアクセスできないようにする
  # find_byを使ったのは、例外を発生させるため
  def correct_user
    # user = User.find(params[:id])
    user = User.find_by(id: params[:id])
    if user != current_user
      redirect_to new_session_path
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email,
                                :password,
                                :password_confirmation,
                                :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bblogs_helper.rb
module BblogsHelper
    def choose_new_or_edit
        if action_name == "new" || action_name == "confirm"
            confirm_bblogs_path
        elsif action_name == "edit"
            bblog_path
        end
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # ログインしていないなら、Userテーブルからユーザー情報を引っ張ってくる
  def current_user
    @current_user || (@current_user = User.find_by(id: session[:user_id]))
  end
  
  # ログイン状態ならtrue、ログインしていないならfalse
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bblogs/_form.html.erb
<%= form_with(model:@bblog, local:true, url:choose_new_or_edit,html:  {multipart: true}) do |form| %>
    <% if @bblog.errors.any? %>
        <div id="error_explanation">
            <h2><%= @bblog.errors.count %>件のエラーがあります</h2>
            
            <ul>
                <% @bblog.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="blog_title">
        <%= form.label :"タイトル" %>
        <%= form.text_field :name %>
    </div>
    <div class="blog_title">
        <%= form.label :"内容" %>
        <%= form.text_field :content %>
    </div>
    <div class="blog_title">
        <%= form.label :"画像" %>
        <%= form.file_field :image, id: :bblog_image %>
        <%= form.hidden_field :image_cache %>
    </div>
    <!--
    ログインユーザー以外、登録できないようにする
    -->
    <% if logged_in? %>
        <%= form.submit "登録する", class:"btn btn-default" %>
    <% end %>

<% end %>

<%= link_to "ブログ一覧ページに戻る", bblogs_path %>

app/views/bblogs/confirm.html.erb
<h3>以下の内容で登録しますか</h3>

<%= form_with(model: @bblog, url: bblogs_path, local: true) do |form| %>
<%= form.hidden_field :name %>
<%= form.hidden_field :content %>

<p>タイトル...<%= @bblog.name %></p>
<p>本文...<%= @bblog.content %></p>
<p>画像...<%= hidden_field_tag :"cache[image]", @bblog.image.cache_name %>
<%= image_tag(@bblog.image.url) %></p>
<%= form.submit "登録するぜ" , class:"btn btn-success"%>
<% end %>

<%= form_with(model: @bblog, local: true, url: new_bblog_path, method: "get") do |form| %>
    <%= form.hidden_field :name %>
    <%= form.hidden_field :content %>
    <%= form.submit "書き直す" , name: "back" , class:"btn btn-danger"%>
<% end %>

app/views/bblogs/edit.html.erb
<!--<%= form_with(model: @bblog, local: true) do |form| %>-->
<!--  <% if @bblog.errors.any? %>-->
<!--  <div id ="error_explanation">-->
<!--    <h2><%= @bblog.errors.count %>件のエラーがあります。</h2>-->
    
<!--    <ul>-->
<!--    <% @bblog.errors.full_messages.each do |msg| %>-->
<!--      <li><%= msg %></li>-->
<!--    <% end %>-->
<!--    </ul>-->
<!--  </div>-->
<!--  <% end %>-->
  
<!--  <div class="blog_title">-->
<!--      <%= form.label :titleName %>-->
<!--      <%= form.text_field :name %>-->
<!--  </div>-->
<!--  <div class="blog_title">-->
<!--      <%= form.label :content %>-->
<!--      <%= form.text_field :content%>-->
<!--  </div>-->
<!--  <%= form.submit %>-->
<!--<% end %>-->
<h2>ブログを編集します</h2>

<%= render "form" %>

app/views/bblogs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 blog-panel">
      <h1>ブログ一覧</h1>
      
      <p><%= notice %></p>
  
    <!--<div class="table-responsive">-->
      <table class="table table-striped">
          <tr>
              <th>タイトル</th>
              <th>内容</th>
              <th>詳細</th>
              <th>編集</th>
              <th>削除</th>
          </tr>
          
      <% @bblogs.each do |blog| %>
          <tr>
              <td><%= blog.name %></td>
              <td><%= blog.content %></td>
              <td><%= link_to "詳細確認", bblog_path(blog.id), class: "btn btn-default" %></td>
              <!--
              投稿ユーザーだけが、編集・削除できるように
              -->
                <% if logged_in? && blog.user_id == current_user.id %>
                  <td><%= link_to "編集", edit_bblog_path(blog.id), class: "btn btn-info" %></td>
                  <td><%= link_to "削除", bblog_path(blog.id), method: :delete ,data: {confirm: "本当に消してもいいですか"}, class:"btn btn-danger" %></td>
              <% else %>
                <td class="yoko">編集</td>
                <td class="yoko">削除</td>
              <% end %>
          </tr>
      <% end %>
      </table>
      
      <h2>
        <%= link_to "ブログ新規作成ページへ", new_bblog_path %>
      </h2>

    </div>
  </div>
</div>

app/views/bblogs/new.html.erb
<!--<%= form_with(model: @bblog, local: true) do |form| %>-->
<!--  <% if @bblog.errors.any? %>-->
<!--  <div id ="error_explanation">-->
<!--    <h2><%= @bblog.errors.count %>件のエラーがあります。</h2>-->
    
<!--    <ul>-->
<!--    <% @bblog.errors.full_messages.each do |msg| %>-->
<!--      <li><%= msg %></li>-->
<!--    <% end %>-->
<!--    </ul>-->
<!--  </div>-->
<!--  <% end %>-->
  
<!--  <div class="blog_title">-->
<!--      <%= form.label :titleName %>-->
<!--      <%= form.text_field :name %>-->
<!--  </div>-->
<!--  <div class="blog_title">-->
<!--      <%= form.label :content %>-->
<!--      <%= form.text_field :content%>-->
<!--  </div>-->
<!--  <%= form.submit %>-->
<!--<% end %>-->
<h2>以下のフォームからブログを作成してね</h2>

<%= render "form" %>

app/views/bblogs/show.html.erb
<h1>ブログ詳細画面</h1>
<!--

-->
<p>タイトル:<%= @bblog.name %></p>
<p>内容:<%= @bblog.content %></p>
<% if @bblog.image? %>
  <p>画像:<%= image_tag @bblog.image.url %></p>
<% end %>
<!--
お気に入りと解除
ログインしないで直リンでアクセスした場合、ログイン画面に飛ばしているため、
current_userは必ず存在する
-->
<% unless @bblog.favorite_users == current_user %>
  <% if @favorite.present? %>
    <%= link_to "お気に入り解除", favorite_path(bblog_id: @bblog.id),
                                method: :delete,
                                class: "btn btn-danger" %>
  <% else %>
    <%= link_to "お気に入りする", favorites_path(bblog_id: @bblog.id),
                                method: :post,
                                class: "btn btn-prymary" %>
  <% end %>
<% end %>

app/views/home/index.html.erb
<!DOCTYPE html>

<h1>BlogApp</h1>
<!--
https://rarararails-miyasu.c9users.io/bblogs/home/index
上記アドレスをトップページにした
(rootの設定はtcloneでやったので、bblogappでは設定してない)
<p>Find me in app/views/home/index.html.erb</p>
-->
<p>Bootstrapシリーズ課題2</p>

  <section class="main-header">
    <img src="/assets/bblog_top.jpg">
  </section>
  
  <section class="about">
    <h1>About</h1>
    <p>
      Rails & Bootstrap & login練習用アプリ<br>
      Railsシリーズ課題で作成したblogappに機能追加する形で実装
      login機能を付加
    </p>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bblogapp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header>
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
              <span class="sr-only">メニュー</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <img class="navbar-brand2" src="/assets/bblog_head_foot.jpg">
          </div>

          <div id="gnavi" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="/bblogs/home/index">TopPage</a></li>
              <li><a href="/bblogs">投稿記事</a></li>
      
              <% if logged_in? %>
                <li><%= link_to "ユーザー情報", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id),
                  method: :delete %></li>
              <% else %>
                <li><%= link_to "新規登録", new_user_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <!--
    フラッシュメッセージの表示
    -->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class:"alert alert-#{key}") %>
    <% end %>
    
    <%= yield %>
    
    <footer>
      <div class="footer-div">
      <ul>
        <li><img src="/assets/bblog_head_foot.jpg"></li>
        <li>10月期tanaka</li>
        <li>(c)tanaka</li>
      </ul>
      </div>
    </footer>
    
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="class_explanation">
    <%= pluralize(@user.errors.count, "error") %>
    <ul>
      <% @user.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 blog-panel">

<%= form_with(model: @user, local: true) do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  
  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.label :image %>
  <%= f.file_field :image, id: :user_image %>
  
  <%= f.label :password %>
  <%= f.password_field :password %>
  
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit "登録する" %>
<% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-6 blog-panel">
      <!--
      登録ユーザー情報
      -->
      <h1><%= @user.name %>のページ</h1>
      <p>メールアドレス...<%= @user.email %></p>
      <% if @user.image? %>
        <p>画像...<%= image_tag @user.image.url %></p>
      <% end %>
      
      <!--
      お気に入りしたblog一覧
      タイトルと内容を表示しているだけ
      -->
      <table class="table table-striped">
          <tr>
              <th>お気に入りblogのタイトル</th>
              <th>お気に入りblogの内容</th>
          </tr>
          
      <% @favorite_bblogs.each do |blog| %>
          <tr>
              <td><%= blog.name %></td>
              <td><%= blog.content %></td>
          </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>